create database management;
use management;
CREATE TABLE STUDENT_INFORMATION(
ID INT NOT NULL,
NAME_OF_STUDENT VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
BLOOD_GROUP VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);
DELETE FROM STUDENT_INFORMATION WHERE BLOOD_GROUP;
SELECT* FROM STUDENT_INFORMATION;
DESCRIBE STUDENT_INFORMATION;
INSERT INTO STUDENT_INFORMATION VALUES('7688','KADHIR','20','DINDIGUL-5');

CREATE TABLE COLLEGE(
COLLEGE_NAME VARCHAR(255) NOT NULL,
COLLEGE_CODE INT NOT NULL,
LOCATION VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(255)
);
SELECT*FROM COLLEGE;
ALTER TABLE COLLEGE ADD EMAIL VARCHAR(255);
INSERT INTO COLLEGE VALUES('ABC COLLEGE','56657','DINDIGUL','33/2 K NAGAR DINDIGUL','abccollege@gmail.com');
CREATE TABLE COURSE (
DEPARTMENT VARCHAR(50) NOT NULL,
SUBJECT_CODE  INT NOT NULL,
COURSE_FEES INT NOT NULL,
COURSE_CODE INT NOT NULL
);
INSERT INTO COURSE VALUES('ELECTRICAL AND ELECTRONICS','5021','25000','8867');
SHOW TABLES;
DESCRIBE COLLEGE;
DESCRIBE COURSE;
DESCRIBE student_information;









