create database management;
use management;
CREATE TABLE STUDENT_INFORMATION(
ID INT NOT NULL,
NAME_OF_STUDENT VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
BLOOD_GROUP VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);
DELETE FROM STUDENT_INFORMATION WHERE BLOOD_GROUP;
SELECT* FROM STUDENT_INFORMATION;
DESCRIBE STUDENT_INFORMATION;
INSERT INTO management.STUDENT_INFORMATION(NAME_OF_STUDENT,AGE,ADDRESS)
 VALUES(100,"KADHIR",20,"DINDIGUL"),
(101,"SURESH",20,"TRICHY"),(103,"RAJESH",20,"MADURAI");
CREATE TABLE COLLEGE(
COLLEGE_NAME VARCHAR(255) NOT NULL,
COLLEGE_CODE INT NOT NULL,
LOCATION VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(255)
);
SELECT*FROM COLLEGE;
ALTER TABLE COLLEGE ADD EMAIL VARCHAR(255);
INSERT INTO management.COLLEGE(COLLEGE_NAME,COLLEGE_CODE,LOCATION,ADDRESS)
 VALUES("ABC COLLEGE",5665,"DINDIGUL","K NAGAR DINDIGUL"),
("BCA COLLEGE",5777,"TRICHI","V NAGAR TRICHY"),
("CAB COLLEGE",9864,"MADURAI","C NAGAR MADURAI");
CREATE TABLE COURSE (
DEPARTMENT VARCHAR(50) NOT NULL,
SUBJECT_CODE  INT NOT NULL,
COURSE_FEES INT NOT NULL,
COURSE_CODE INT NOT NULL
);
INSERT INTO management.COURSE(DEPARTMENT,SUBJECT_CODE,COURSE_FEES,COURSE_CODE)
 VALUES("ELECTRICAL AND ELECTRONICS",5021,25000,8867),
("COMPUTER SCIENCE",5022,25000,8868),("INFORMATION TECHNOLOGY",5023,25000,8869);
SHOW TABLES;
DESCRIBE COLLEGE;
DESCRIBE COURSE;
DESCRIBE student_information;









